"""Transform models — define answer migration rules between template versions.

When a tenant publishes a new TenantTemplateDefinition, a TransformRuleSet can
be created (manually or auto-generated by the diff service) to describe how
in-flight submission answers should be migrated from the old version to the new.

Model hierarchy
---------------
TransformRuleSet  1 ── * TransformRule
TransformRuleSet  1 ── * TransformLog

Lifecycle
---------
  draft ──► published ──► archived
  (editable)  (frozen)   (superseded)
"""

import uuid as _uuid
from datetime import datetime
from typing import Any, Dict, List, Optional

from sqlalchemy import Column, Enum as SAEnum, Text
from sqlmodel import Field, JSON, Relationship
from uuid_extensions import uuid7

from app.models.base import TenantSchemaModel
from app.models.enums import RuleSetStatus, TransformOperation


class TransformRuleSet(TenantSchemaModel, table=True):
    """A versioned set of transform rules mapping source → target template version.

    One ruleset covers the full migration path from source_version_id to
    target_version_id.  A ruleset may be auto-generated by the diff service
    (auto_generated=True) and then manually refined before publishing.

    Unique constraint: (source_version_id, target_version_id) ensures only one
    published ruleset exists per version pair.
    """

    __tablename__ = "transform_rule_sets"

    id: _uuid.UUID = Field(
        default_factory=uuid7,
        primary_key=True,
        nullable=False,
    )

    template_id: _uuid.UUID = Field(
        foreign_key="tenant_templates.id",
        index=True,
        nullable=False,
        description="The template both versions belong to.",
    )

    source_version_id: _uuid.UUID = Field(
        foreign_key="tenant_template_definitions.id",
        index=True,
        nullable=False,
        description="The old template version whose answers will be migrated.",
    )

    target_version_id: _uuid.UUID = Field(
        foreign_key="tenant_template_definitions.id",
        index=True,
        nullable=False,
        description="The new template version answers will be migrated into.",
    )

    status: RuleSetStatus = Field(
        default=RuleSetStatus.DRAFT,
        sa_column=Column(
            SAEnum(
                RuleSetStatus,
                values_callable=lambda obj: [e.value for e in obj],
                name="rulesetstatus",
                create_type=False,
            ),
            nullable=False,
            server_default="draft",
        ),
        description="draft | published | archived",
    )

    auto_generated: bool = Field(
        default=False,
        description="True when created automatically by the version-diff service.",
    )

    changelog: Optional[str] = Field(
        default=None,
        sa_column=Column(Text),
        description="Human-readable description of what changed between versions.",
    )

    rules: List["TransformRule"] = Relationship(
        back_populates="rule_set",
        sa_relationship_kwargs={
            "cascade": "all, delete-orphan",
            "order_by": "TransformRule.display_order",
        },
    )

    logs: List["TransformLog"] = Relationship(
        back_populates="rule_set",
        sa_relationship_kwargs={"cascade": "all, delete-orphan"},
    )


class TransformRule(TenantSchemaModel, table=True):
    """A single answer-mapping rule within a TransformRuleSet.

    Each rule describes how one source question's answer (identified by
    unique_key in the source version) is converted into an answer for the
    target question (identified by unique_key in the target version).

    Special cases
    -------------
    - MERGE: source_unique_key is unused; target receives all sources listed in
      params["sources"].
    - SPLIT: multiple rules share source_unique_key; each rule's params["index"]
      picks the piece.
    - DEFAULT_VALUE / DROP: source_unique_key may be null (no source question).
    """

    __tablename__ = "transform_rules"

    id: _uuid.UUID = Field(
        default_factory=uuid7,
        primary_key=True,
        nullable=False,
    )

    rule_set_id: _uuid.UUID = Field(
        foreign_key="transform_rule_sets.id",
        index=True,
        nullable=False,
    )

    source_unique_key: Optional[str] = Field(
        default=None,
        max_length=255,
        description="unique_key of the question in the source version. "
                    "Null for DEFAULT_VALUE and DROP when there is no source.",
    )

    target_unique_key: str = Field(
        max_length=255,
        description="unique_key of the question in the target version.",
    )

    operation: TransformOperation = Field(
        sa_column=Column(
            SAEnum(
                TransformOperation,
                values_callable=lambda obj: [e.value for e in obj],
                name="transformoperation",
                create_type=False,
            ),
            nullable=False,
        ),
        description="The transform operation to apply.",
    )

    params: Dict[str, Any] = Field(
        default_factory=dict,
        sa_type=JSON,
        description="Operation-specific parameters (see TransformOperation docs).",
    )

    display_order: int = Field(
        default=0,
        description="Execution order within the rule set.",
    )

    is_required: bool = Field(
        default=False,
        description="If True, a failed transform blocks the migration entirely.",
    )

    rule_set: "TransformRuleSet" = Relationship(back_populates="rules")


class TransformLog(TenantSchemaModel, table=True):
    """Immutable audit record of a single transform execution on a submission.

    Written after every apply (including previews — marked with is_preview=True
    so they can be filtered from compliance reports).
    """

    __tablename__ = "transform_logs"

    id: _uuid.UUID = Field(
        default_factory=uuid7,
        primary_key=True,
        nullable=False,
    )

    submission_id: _uuid.UUID = Field(
        foreign_key="submissions.id",
        index=True,
        nullable=False,
    )

    rule_set_id: _uuid.UUID = Field(
        foreign_key="transform_rule_sets.id",
        index=True,
        nullable=False,
    )

    source_version_id: _uuid.UUID = Field(
        foreign_key="tenant_template_definitions.id",
        nullable=False,
    )

    target_version_id: _uuid.UUID = Field(
        foreign_key="tenant_template_definitions.id",
        nullable=False,
    )

    before_snapshot: Dict[str, Any] = Field(
        default_factory=dict,
        sa_type=JSON,
        description="Answers keyed by unique_key before the transform.",
    )

    after_snapshot: Dict[str, Any] = Field(
        default_factory=dict,
        sa_type=JSON,
        description="Answers keyed by unique_key after the transform.",
    )

    errors: List[Any] = Field(
        default_factory=list,
        sa_type=JSON,
        description="List of error dicts produced during transformation.",
    )

    warnings: List[Any] = Field(
        default_factory=list,
        sa_type=JSON,
        description="Non-fatal warnings produced during transformation.",
    )

    applied_at: datetime = Field(
        default_factory=lambda: __import__("datetime").datetime.now(
            __import__("datetime").timezone.utc
        ),
        nullable=False,
        description="UTC timestamp when the transform was applied.",
    )

    applied_by: str = Field(
        max_length=255,
        nullable=False,
        description="User ID or 'system' for bulk migrations.",
    )

    is_preview: bool = Field(
        default=False,
        description="True for dry-run calls; the submission was NOT modified.",
    )

    rule_set: "TransformRuleSet" = Relationship(back_populates="logs")
